# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1200, 900)
        mainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        mainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(50, 50, 50, 50)
        self.mainLayout.setSpacing(50)
        self.mainLayout.setObjectName("mainLayout")
        self.view = View(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view.sizePolicy().hasHeightForWidth())
        self.view.setSizePolicy(sizePolicy)
        self.view.setMinimumSize(QtCore.QSize(700, 700))
        self.view.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 145, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 145, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 145, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 145, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 145, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 145, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.view.setPalette(palette)
        self.view.setObjectName("view")
        self.mainLayout.addWidget(self.view)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(320, 580))
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"stop: 0 rgb(150, 150, 150), stop: 0.4 rgb(135, 135, 135),\n"
"stop: 0.5 rgb(125, 125, 125), stop: 1.0 rgb(110, 110, 110));\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    border-radius: 4px;\n"
"        color: black;\n"
"        padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"        background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 rgb(200, 200, 200), stop: 0.4 rgb(185, 185, 185), stop: 0.5 rgb(175, 175, 175), stop: 1.0 rgb(160, 160, 160));\n"
"}\n"
"QPushButton:pressed {\n"
"        background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 rgb(220, 220, 220), stop: 0.4 rgb(205, 205, 205), stop: 0.5 rgb(195, 195, 195), stop: 1.0 rgb(180, 180, 180));\n"
"}\n"
"QTabWidget::pane {\n"
"    border-top: 1px solid rgb(150, 150, 150);\n"
"}\n"
"QTabWidget::tab-bar {\n"
"    left: 10px;\n"
"}\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 rgb(180, 180, 180), stop: 0.4 rgb(165, 165, 165), stop: 0.5 rgb(155, 155, 155), stop: 1.0 rgb(140, 140, 140));\n"
"    border: 1px solid rgb(150, 150, 150);\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 10ex;\n"
"    padding: 2px;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 rgb(220, 220, 220), stop: 0.4 rgb(205, 205, 205), stop: 0.5 rgb(195, 195, 195), stop: 1.0 rgb(180, 180, 180));\n"
"}\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px;\n"
"}\n"
"QTabBar::tab:selected {\n"
"    margin-left: -4px;\n"
"    margin-right: -4px;\n"
"}\n"
"QTabBar::tab:first:selected {\n"
"    margin-left: 0;\n"
"}\n"
"QTabBar::tab:last:selected {\n"
"    margin-right: 0;\n"
"}\n"
"QTabBar::tab:only-one {\n"
"    margin: 0;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.moveListTab = QtWidgets.QWidget()
        self.moveListTab.setObjectName("moveListTab")
        self.layoutWidget = QtWidgets.QWidget(self.moveListTab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 302, 542))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.commentField = CommentEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentField.sizePolicy().hasHeightForWidth())
        self.commentField.setSizePolicy(sizePolicy)
        self.commentField.setMinimumSize(QtCore.QSize(300, 90))
        self.commentField.setMaximumSize(QtCore.QSize(16777215, 90))
        self.commentField.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.commentField.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.commentField.setObjectName("commentField")
        self.verticalLayout_2.addWidget(self.commentField)
        self.moveListWidget = QtWidgets.QListWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveListWidget.sizePolicy().hasHeightForWidth())
        self.moveListWidget.setSizePolicy(sizePolicy)
        self.moveListWidget.setMinimumSize(QtCore.QSize(300, 400))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.moveListWidget.setFont(font)
        self.moveListWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.moveListWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.moveListWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.moveListWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.moveListWidget.setProperty("showDropIndicator", False)
        self.moveListWidget.setObjectName("moveListWidget")
        self.verticalLayout_2.addWidget(self.moveListWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.firstMoveButton = QtWidgets.QPushButton(self.layoutWidget)
        self.firstMoveButton.setObjectName("firstMoveButton")
        self.horizontalLayout_2.addWidget(self.firstMoveButton)
        self.prevMoveButton = QtWidgets.QPushButton(self.layoutWidget)
        self.prevMoveButton.setObjectName("prevMoveButton")
        self.horizontalLayout_2.addWidget(self.prevMoveButton)
        self.nextMoveButton = QtWidgets.QPushButton(self.layoutWidget)
        self.nextMoveButton.setObjectName("nextMoveButton")
        self.horizontalLayout_2.addWidget(self.nextMoveButton)
        self.lastMoveButton = QtWidgets.QPushButton(self.layoutWidget)
        self.lastMoveButton.setObjectName("lastMoveButton")
        self.horizontalLayout_2.addWidget(self.lastMoveButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.moveListTab, "")
        self.pgnTab = QtWidgets.QWidget()
        self.pgnTab.setObjectName("pgnTab")
        self.layoutWidget1 = QtWidgets.QWidget(self.pgnTab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 302, 542))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pgnField = QtWidgets.QPlainTextEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pgnField.sizePolicy().hasHeightForWidth())
        self.pgnField.setSizePolicy(sizePolicy)
        self.pgnField.setMinimumSize(QtCore.QSize(300, 500))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        self.pgnField.setFont(font)
        self.pgnField.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pgnField.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pgnField.setObjectName("pgnField")
        self.verticalLayout_4.addWidget(self.pgnField)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.loadPgnButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.loadPgnButton.setObjectName("loadPgnButton")
        self.horizontalLayout_3.addWidget(self.loadPgnButton)
        self.savePgnButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.savePgnButton.setEnabled(True)
        self.savePgnButton.setObjectName("savePgnButton")
        self.horizontalLayout_3.addWidget(self.savePgnButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.pgnTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.fenGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fenGroupBox.sizePolicy().hasHeightForWidth())
        self.fenGroupBox.setSizePolicy(sizePolicy)
        self.fenGroupBox.setMinimumSize(QtCore.QSize(320, 110))
        self.fenGroupBox.setStyleSheet("QGroupBox {\n"
"        background: none;\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 rgb(150, 150, 150), stop: 0.4 rgb(135, 135, 135), stop: 0.5 rgb(125, 125, 125), stop: 1.0 rgb(110, 110, 110));\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    border-radius: 4px;\n"
"        color: black;\n"
"        padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"        background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 rgb(200, 200, 200), stop: 0.4 rgb(185, 185, 185), stop: 0.5 rgb(175, 175, 175), stop: 1.0 rgb(160, 160, 160));\n"
"}\n"
"QPushButton:pressed {\n"
"        background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 rgb(220, 220, 220), stop: 0.4 rgb(205, 205, 205), stop: 0.5 rgb(195, 195, 195), stop: 1.0 rgb(180, 180, 180));\n"
"}\n"
"QPushButton#boardResetButton {\n"
"    font-weight: bold;\n"
"}")
        self.fenGroupBox.setObjectName("fenGroupBox")
        self.layoutWidget2 = QtWidgets.QWidget(self.fenGroupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 302, 72))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fenField = QtWidgets.QPlainTextEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fenField.sizePolicy().hasHeightForWidth())
        self.fenField.setSizePolicy(sizePolicy)
        self.fenField.setMinimumSize(QtCore.QSize(300, 0))
        self.fenField.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        self.fenField.setFont(font)
        self.fenField.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.fenField.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fenField.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.fenField.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.fenField.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.fenField.setObjectName("fenField")
        self.verticalLayout_3.addWidget(self.fenField)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.setFenButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.setFenButton.setObjectName("setFenButton")
        self.horizontalLayout.addWidget(self.setFenButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.boardResetButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.boardResetButton.setObjectName("boardResetButton")
        self.horizontalLayout.addWidget(self.boardResetButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.fenGroupBox)
        self.mainLayout.addLayout(self.verticalLayout)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menu4PlayerChess = QtWidgets.QMenu(self.menubar)
        self.menu4PlayerChess.setObjectName("menu4PlayerChess")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"color: grey;")
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Game = QtWidgets.QAction(mainWindow)
        self.actionLoad_Game.setObjectName("actionLoad_Game")
        self.actionSave_Game_As = QtWidgets.QAction(mainWindow)
        self.actionSave_Game_As.setObjectName("actionSave_Game_As")
        self.actionQuit = QtWidgets.QAction(mainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionCopy_FEN4 = QtWidgets.QAction(mainWindow)
        self.actionCopy_FEN4.setObjectName("actionCopy_FEN4")
        self.actionPaste_FEN4 = QtWidgets.QAction(mainWindow)
        self.actionPaste_FEN4.setObjectName("actionPaste_FEN4")
        self.actionRotate_Board_Left = QtWidgets.QAction(mainWindow)
        self.actionRotate_Board_Left.setObjectName("actionRotate_Board_Left")
        self.actionRotate_Board_Right = QtWidgets.QAction(mainWindow)
        self.actionRotate_Board_Right.setObjectName("actionRotate_Board_Right")
        self.actionFlip_Board = QtWidgets.QAction(mainWindow)
        self.actionFlip_Board.setObjectName("actionFlip_Board")
        self.actionNew_Game = QtWidgets.QAction(mainWindow)
        self.actionNew_Game.setObjectName("actionNew_Game")
        self.actionAbout = QtWidgets.QAction(mainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionPreferences = QtWidgets.QAction(mainWindow)
        self.actionPreferences.setEnabled(False)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionCheck_for_Updates = QtWidgets.QAction(mainWindow)
        self.actionCheck_for_Updates.setEnabled(False)
        self.actionCheck_for_Updates.setObjectName("actionCheck_for_Updates")
        self.menuFile.addAction(self.actionNew_Game)
        self.menuFile.addAction(self.actionLoad_Game)
        self.menuFile.addAction(self.actionSave_Game_As)
        self.menuEdit.addAction(self.actionCopy_FEN4)
        self.menuEdit.addAction(self.actionPaste_FEN4)
        self.menuView.addAction(self.actionRotate_Board_Left)
        self.menuView.addAction(self.actionRotate_Board_Right)
        self.menuView.addAction(self.actionFlip_Board)
        self.menu4PlayerChess.addAction(self.actionAbout)
        self.menu4PlayerChess.addAction(self.actionCheck_for_Updates)
        self.menu4PlayerChess.addAction(self.actionPreferences)
        self.menu4PlayerChess.addSeparator()
        self.menu4PlayerChess.addAction(self.actionQuit)
        self.menubar.addAction(self.menu4PlayerChess.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "4PlayerChess"))
        self.commentField.setPlaceholderText(_translate("mainWindow", "Enter comment for this move..."))
        self.firstMoveButton.setStatusTip(_translate("mainWindow", "Go to first move"))
        self.firstMoveButton.setText(_translate("mainWindow", "|<"))
        self.prevMoveButton.setStatusTip(_translate("mainWindow", "Go to previous move"))
        self.prevMoveButton.setText(_translate("mainWindow", "<"))
        self.nextMoveButton.setStatusTip(_translate("mainWindow", "Go to next move"))
        self.nextMoveButton.setText(_translate("mainWindow", ">"))
        self.lastMoveButton.setStatusTip(_translate("mainWindow", "Go to last move"))
        self.lastMoveButton.setText(_translate("mainWindow", ">|"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.moveListTab), _translate("mainWindow", "Move List"))
        self.loadPgnButton.setStatusTip(_translate("mainWindow", "Load game from PGN4 file"))
        self.loadPgnButton.setText(_translate("mainWindow", "Load..."))
        self.savePgnButton.setStatusTip(_translate("mainWindow", "Save game to PGN4 file"))
        self.savePgnButton.setText(_translate("mainWindow", "Save As..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pgnTab), _translate("mainWindow", "PGN4"))
        self.fenGroupBox.setTitle(_translate("mainWindow", "Current Position (FEN4):"))
        self.fenField.setStatusTip(_translate("mainWindow", "Enter FEN4"))
        self.fenField.setPlaceholderText(_translate("mainWindow", "Enter FEN4 here..."))
        self.setFenButton.setStatusTip(_translate("mainWindow", "Set position to specified FEN4"))
        self.setFenButton.setText(_translate("mainWindow", "Set Position"))
        self.boardResetButton.setStatusTip(_translate("mainWindow", "Reset board"))
        self.boardResetButton.setText(_translate("mainWindow", "Reset Board"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.menuEdit.setTitle(_translate("mainWindow", "Edit"))
        self.menuView.setTitle(_translate("mainWindow", "View"))
        self.menu4PlayerChess.setTitle(_translate("mainWindow", "4PlayerChess"))
        self.actionLoad_Game.setText(_translate("mainWindow", "Load Game..."))
        self.actionLoad_Game.setToolTip(_translate("mainWindow", "Load Game..."))
        self.actionLoad_Game.setStatusTip(_translate("mainWindow", "Load game from PGN4 file"))
        self.actionLoad_Game.setShortcut(_translate("mainWindow", "Ctrl+O"))
        self.actionSave_Game_As.setText(_translate("mainWindow", "Save Game As..."))
        self.actionSave_Game_As.setToolTip(_translate("mainWindow", "Save Game As..."))
        self.actionSave_Game_As.setStatusTip(_translate("mainWindow", "Save game to PGN4 file"))
        self.actionSave_Game_As.setShortcut(_translate("mainWindow", "Ctrl+Shift+S"))
        self.actionQuit.setText(_translate("mainWindow", "Quit 4PlayerChess"))
        self.actionQuit.setStatusTip(_translate("mainWindow", "Quit application"))
        self.actionQuit.setShortcut(_translate("mainWindow", "Ctrl+Q"))
        self.actionCopy_FEN4.setText(_translate("mainWindow", "Copy FEN4"))
        self.actionCopy_FEN4.setStatusTip(_translate("mainWindow", "Copy FEN4 to clipboard"))
        self.actionCopy_FEN4.setShortcut(_translate("mainWindow", "Ctrl+C"))
        self.actionPaste_FEN4.setText(_translate("mainWindow", "Paste FEN4"))
        self.actionPaste_FEN4.setStatusTip(_translate("mainWindow", "Paste FEN4 from clipboard"))
        self.actionPaste_FEN4.setShortcut(_translate("mainWindow", "Ctrl+V"))
        self.actionRotate_Board_Left.setText(_translate("mainWindow", "Rotate Board Left"))
        self.actionRotate_Board_Left.setStatusTip(_translate("mainWindow", "Rotate board counterclockwise"))
        self.actionRotate_Board_Left.setShortcut(_translate("mainWindow", "Ctrl+L"))
        self.actionRotate_Board_Right.setText(_translate("mainWindow", "Rotate Board Right"))
        self.actionRotate_Board_Right.setStatusTip(_translate("mainWindow", "Rotate board clockwise"))
        self.actionRotate_Board_Right.setShortcut(_translate("mainWindow", "Ctrl+R"))
        self.actionFlip_Board.setText(_translate("mainWindow", "Flip Board"))
        self.actionFlip_Board.setStatusTip(_translate("mainWindow", "Flip board"))
        self.actionFlip_Board.setShortcut(_translate("mainWindow", "Ctrl+F"))
        self.actionNew_Game.setText(_translate("mainWindow", "New Game"))
        self.actionNew_Game.setStatusTip(_translate("mainWindow", "Start new game"))
        self.actionNew_Game.setShortcut(_translate("mainWindow", "Ctrl+N"))
        self.actionAbout.setText(_translate("mainWindow", "About 4PlayerChess"))
        self.actionAbout.setStatusTip(_translate("mainWindow", "Application info"))
        self.actionPreferences.setText(_translate("mainWindow", "Preferences..."))
        self.actionPreferences.setStatusTip(_translate("mainWindow", "Application preferences"))
        self.actionCheck_for_Updates.setText(_translate("mainWindow", "Check for Updates"))
        self.actionCheck_for_Updates.setStatusTip(_translate("mainWindow", "Check if updates are available"))

from gui.view import CommentEdit, View
